name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "Justfile"
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Building all hosts
        run: nix build .




