name: Build Cloud ISO

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "Justfile"

jobs:
  build-live:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v31
      with:
        install_url: https://nixos.org/nix/install
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          experimental-features = nix-command flakes
    - name: "build public iso"
      run: |
        nix build .#nixosConfigurations.cloud-iso.config.formats.install-iso
    - name: "provide default iso"
      uses: actions/upload-artifact@v4
      with:
        name: live-iso
        path: |
          result/*.iso

