name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "Justfile"
      - ".github/workflows/*"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "Justfile"
      - ".github/workflows/*"

jobs:
  checks:
    name: Check expressions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: extractions/setup-just@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run CI job
        run: just ci
  build:
    needs: checks
    strategy:
      fail-fast: true
      matrix:
        host_name: [LCNDWWYVTFMFX, yukikaze, poi, taihou]
        include:
          - host_name: LCNDWWYVTFMFX
            os: macos-latest
          - host_name: yukikaze
            os: macos-latest
          - host_name: poi
            os: ubuntu-latest
          - host_name: taihou
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: extractions/setup-just@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Linux-specific command
        if: runner.os == 'Linux'
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false
      - run: just ci-${{ matrix.host_name }}
