name: Formatting Check

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "Justfile"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "Justfile"

jobs:
  checks:
    name: Check expressions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v24
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run nix fmt
        run: just ci-fmt
