name: Build Outputs
on:
  push:
    branches:
      - master
    paths-ignore:
      - "justfile"
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "justfile"
      - "**.md"

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Install omnix
        run: nix --accept-flake-config profile install "github:juspay/omnix"
      - run: om ci --extra-access-tokens "github.com=${{ secrets.GITHUB_TOKEN }}"
