#!/usr/bin/env python

import subprocess
from typing import List

def _run_cmd(cmd):
    return subprocess.check_output(cmd, shell=True).decode('utf-8').strip()

def get_untracked_files() -> List[str]:
    return _run_cmd("git ls-files --others --exclude-standard").splitlines()

def add_untracked_files():
    untracked_files = get_untracked_files()
    for file in untracked_files:
        _run_cmd(f"git add -N -- {file}")

def get_diff():
    return _run_cmd("git diff HEAD --no-ext-diff")

def get_new_lines():
    diff = get_diff()
    new_lines = [line for line in diff.splitlines() if line.startswith('+')]
    new_lines = [line for line in new_lines if not line.startswith('+++')]
    return new_lines

def main():
    add_untracked_files()
    print("\n".join(get_new_lines()))

if __name__ == "__main__":
    main()
